name: Toota Expo CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0
      
      - name: Set up EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android
        run: eas build --platform android --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # - name: Rename Android APK
      #   run: |
      #     build_url=$(eas build:status --platform android --json | jq -r '.artifacts.buildUrl')
      #     echo "Build URL: $build_url"
      #     curl -L $build_url -o ./builds/toota.apk

      - name: Build iOS
        run: eas build --platform ios --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # - name: Rename iOS IPA
      #   run: |
      #     build_url=$(eas build:status --platform ios --json | jq -r '.artifacts.buildUrl')
      #     echo "Build URL: $build_url"
      #     curl -L $build_url -o ./builds/toota.ipa

      - name: Generate new version tag
        id: version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v1.0.0")
          latest_version=${latest_tag#v}
          new_version=$(echo $latest_version | awk -F. '{print $1"."$2"."$3+1}')
          echo "NEW_VERSION=v$new_version" >> $GITHUB_ENV
          echo "New version: v$new_version"

      - name: Commit build files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update build files ${{ env.NEW_VERSION }} [skip ci]" || echo "No changes to commit"
          git push origin master

      - name: Create Git Tag
        run: |
          git tag -a ${{ env.NEW_VERSION }} -m "Release ${{ env.NEW_VERSION }}"
          git push origin ${{ env.NEW_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: "Release ${{ env.NEW_VERSION }}"
          body: "🚀 New build available!"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Clean Up Old Builds
      #   run: |
      #     find builds -type f -name "*.apk" -mtime +1 -delete
      #     find builds -type f -name "*.ipa" -mtime +1 -delete
      #     git add builds/
      #     git commit -m "Cleanup old builds" || echo "No old builds to delete"
      #     git push origin master || echo "Nothing to push"
